const root = new URL("..", import.meta.url).pathname;
const appDirectory = `${root}/app`;
const source = `${appDirectory}/praxis-studio.ts`;
const browserArtifact = "praxis-studio.browser.js";

export async function buildApp() {
  const result = await Bun.build({
    entrypoints: [source],
    outdir: appDirectory,
    naming: browserArtifact,
    target: "browser",
    banner: "// Generated from app/praxis-studio.ts. Do not edit this file directly."
  });

  if (!result.success) {
    for (const log of result.logs) console.error(log);
    throw new Error("Unable to build the Praxis Studio browser application.");
  }
}

if (import.meta.main) {
  await buildApp();
  console.log(`Built app/${browserArtifact}`);
}
